# config.yaml

samples:
  - TH1
  - TH2

merge_name: cNeurog2

filter_params:
  nATAC_max: 60000
  nRNA_max: 40000
  nATAC_min: 100
  nRNA_min: 1000
  nFeature_RNA_min: 500
  nucleosome_signal_max: 2
  percent_mt_max: 10
  tss: 0

markers_file: markers
annotations_file: annotations.txt
gtf_file: neurog2.gtf
diffpeaks_file: cNeurog2DiffPeaks.csv
diffpeaks_annotated: cNeurog2DiffPeaks_annotated.csv
peak_plot: toppeaks.png

